name: GitHub Pages action

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
        env:
          REACT_APP_GITHUB_KEY: ${{ secrets.REACT_APP_GITHUB_KEY }}
